# Binding C-a instead of C-b
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Adding mouse scroll support
set -g mouse on

# A shortcut for reloading tmux config
bind r source-file ~/.tmux.conf

#status bar customization
set -g set-titles on
set -g default-terminal "screen-256color"

# Vim bindings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind y run-shell "tmux show-buffer | pbcopy" \; display-message "Copied tmux buffer to system clipboard"

# Remap window navigation to vim
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R

# Add truecolor support
set-option -ga terminal-overrides ",xterm-256color:Tc"
# Default terminal is 256 colors
set -g default-terminal "screen-256color"
